### ISSUE TITLE
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by err-or** [GlassyWing/yolo_deepsort#11]
Hi I have been trying to run the repo in google colab with gpu. When I execute "video_deepsort.py" I get the following error: 

2020-07-24 06:02:19,815 - INFO - Reading config...
2020-07-24 06:02:20,276 - INFO - Reading config done
Loading weights from weights/ckpt.t7... Done!
2020-07-24 06:02:24,310 - INFO - Detect video: data/test.mp4
2020-07-24 06:02:24,355 - INFO - Output Type: ../data/output.mp4, 828601953, 30, (1920, 1080)
2020-07-24 06:02:24,533 - INFO - 	 Inference time: 0:00:00.072129
2020-07-24 06:02:24,616 - INFO - 	 Inference time: 0:00:00.046835
2020-07-24 06:02:24,697 - INFO - 	 Inference time: 0:00:00.041138
2020-07-24 06:02:24,762 - INFO - 	 Inference time: 0:00:00.032771
2020-07-24 06:02:24,864 - INFO - 	 Inference time: 0:00:00.057584
2020-07-24 06:02:24,939 - INFO - 	 Inference time: 0:00:00.037254
2020-07-24 06:02:24,998 - INFO - 	 Inference time: 0:00:00.030447
2020-07-24 06:02:25,090 - INFO - 	 Inference time: 0:00:00.057867
2020-07-24 06:02:25,161 - INFO - 	 Inference time: 0:00:00.046764
2020-07-24 06:02:25,231 - INFO - 	 Inference time: 0:00:00.032764
2020-07-24 06:02:25,283 - INFO - 	 Inference time: 0:00:00.029539
2020-07-24 06:02:25,370 - INFO - 	 Inference time: 0:00:00.061455
FPS: 23
2020-07-24 06:02:25,468 - INFO - 	 Inference time: 0:00:00.050386
2020-07-24 06:02:25,580 - INFO - 	 Inference time: 0:00:00.055735
2020-07-24 06:02:25,647 - INFO - 	 Inference time: 0:00:00.038648
2020-07-24 06:02:25,708 - INFO - 	 Inference time: 0:00:00.030106
2020-07-24 06:02:25,763 - INFO - 	 Inference time: 0:00:00.030028
2020-07-24 06:02:25,840 - INFO - 	 Inference time: 0:00:00.049671
2020-07-24 06:02:25,898 - INFO - 	 Inference time: 0:00:00.030984
2020-07-24 06:02:25,965 - INFO - 	 Inference time: 0:00:00.037194
2020-07-24 06:02:26,085 - INFO - 	 Inference time: 0:00:00.046189
2020-07-24 06:02:26,170 - INFO - 	 Inference time: 0:00:00.048173
2020-07-24 06:02:26,237 - INFO - 	 Inference time: 0:00:00.031856
2020-07-24 06:02:26,296 - INFO - 	 Inference time: 0:00:00.030107
2020-07-24 06:02:26,383 - INFO - 	 Inference time: 0:00:00.063005
FPS: 26
2020-07-24 06:02:26,465 - INFO - 	 Inference time: 0:00:00.042469
2020-07-24 06:02:26,521 - INFO - 	 Inference time: 0:00:00.029568
2020-07-24 06:02:26,578 - INFO - 	 Inference time: 0:00:00.030526
2020-07-24 06:02:26,638 - INFO - 	 Inference time: 0:00:00.030534
2020-07-24 06:02:26,703 - INFO - 	 Inference time: 0:00:00.030067
2020-07-24 06:02:26,781 - INFO - 	 Inference time: 0:00:00.049437
2020-07-24 06:02:26,877 - INFO - 	 Inference time: 0:00:00.058676
2020-07-24 06:02:26,984 - INFO - 	 Inference time: 0:00:00.037252
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/imutils/video/filevideostream.py", line 67, in update
    frame = self.transform(frame)
  File "/content/yolo_deepsort/yolo3/detect/video_detect.py", line 34, in _transform
    return cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

2020-07-24 06:02:27,088 - INFO - 	 Inference time: 0:00:00.036465
2020-07-24 06:02:27,138 - INFO - 	 Inference time: 0:00:00.025053
2020-07-24 06:02:27,189 - INFO - 	 Inference time: 0:00:00.024349
2020-07-24 06:02:27,238 - INFO - 	 Inference time: 0:00:00.023730
2020-07-24 06:02:27,285 - INFO - 	 Inference time: 0:00:00.024008
2020-07-24 06:02:27,332 - INFO - 	 Inference time: 0:00:00.023859
2020-07-24 06:02:27,379 - INFO - 	 Inference time: 0:00:00.023900
FPS: 30
2020-07-24 06:02:27,427 - INFO - 	 Inference time: 0:00:00.023751
2020-07-24 06:02:27,476 - INFO - 	 Inference time: 0:00:00.023747
2020-07-24 06:02:27,525 - INFO - 	 Inference time: 0:00:00.024034
2020-07-24 06:02:27,578 - INFO - 	 Inference time: 0:00:00.023974
2020-07-24 06:02:27,625 - INFO - 	 Inference time: 0:00:00.023888
2020-07-24 06:02:27,675 - INFO - 	 Inference time: 0:00:00.024328
2020-07-24 06:02:27,724 - INFO - 	 Inference time: 0:00:00.023467
2020-07-24 06:02:27,773 - INFO - 	 Inference time: 0:00:00.023828
2020-07-24 06:02:27,821 - INFO - 	 Inference time: 0:00:00.023553
2020-07-24 06:02:27,876 - INFO - 	 Inference time: 0:00:00.024036
2020-07-24 06:02:27,929 - INFO - 	 Inference time: 0:00:00.023671
2020-07-24 06:02:27,986 - INFO - 	 Inference time: 0:00:00.026806
2020-07-24 06:02:28,037 - INFO - 	 Inference time: 0:00:00.023839
2020-07-24 06:02:28,092 - INFO - 	 Inference time: 0:00:00.023777
2020-07-24 06:02:28,141 - INFO - 	 Inference time: 0:00:00.024310
2020-07-24 06:02:28,190 - INFO - 	 Inference time: 0:00:00.023869
2020-07-24 06:02:28,241 - INFO - 	 Inference time: 0:00:00.024323
2020-07-24 06:02:28,293 - INFO - 	 Inference time: 0:00:00.024464
2020-07-24 06:02:28,350 - INFO - 	 Inference time: 0:00:00.026074
FPS: 38
2020-07-24 06:02:28,409 - INFO - 	 Inference time: 0:00:00.027308
2020-07-24 06:02:28,465 - INFO - 	 Inference time: 0:00:00.023894
2020-07-24 06:02:28,520 - INFO - 	 Inference time: 0:00:00.023870
2020-07-24 06:02:28,579 - INFO - 	 Inference time: 0:00:00.025258
2020-07-24 06:02:28,635 - INFO - 	 Inference time: 0:00:00.023769
2020-07-24 06:02:28,689 - INFO - 	 Inference time: 0:00:00.024628
2020-07-24 06:02:28,742 - INFO - 	 Inference time: 0:00:00.024018
2020-07-24 06:02:28,795 - INFO - 	 Inference time: 0:00:00.023710
2020-07-24 06:02:28,850 - INFO - 	 Inference time: 0:00:00.024600
2020-07-24 06:02:28,905 - INFO - 	 Inference time: 0:00:00.028612
2020-07-24 06:02:28,956 - INFO - 	 Inference time: 0:00:00.023884
2020-07-24 06:02:29,009 - INFO - 	 Inference time: 0:00:00.024233
2020-07-24 06:02:29,062 - INFO - 	 Inference time: 0:00:00.023808
2020-07-24 06:02:29,117 - INFO - 	 Inference time: 0:00:00.023849
2020-07-24 06:02:29,170 - INFO - 	 Inference time: 0:00:00.023648
2020-07-24 06:02:29,224 - INFO - 	 Inference time: 0:00:00.023403
2020-07-24 06:02:29,281 - INFO - 	 Inference time: 0:00:00.024250
2020-07-24 06:02:29,338 - INFO - 	 Inference time: 0:00:00.024134
FPS: 36
2020-07-24 06:02:29,392 - INFO - 	 Inference time: 0:00:00.023779
2020-07-24 06:02:29,446 - INFO - 	 Inference time: 0:00:00.023504
2020-07-24 06:02:29,501 - INFO - 	 Inference time: 0:00:00.024275
2020-07-24 06:02:29,555 - INFO - 	 Inference time: 0:00:00.023809
2020-07-24 06:02:29,608 - INFO - 	 Inference time: 0:00:00.023458
2020-07-24 06:02:29,664 - INFO - 	 Inference time: 0:00:00.024181
2020-07-24 06:02:29,720 - INFO - 	 Inference time: 0:00:00.023965
2020-07-24 06:02:29,776 - INFO - 	 Inference time: 0:00:00.025904
2020-07-24 06:02:29,836 - INFO - 	 Inference time: 0:00:00.024041
2020-07-24 06:02:29,890 - INFO - 	 Inference time: 0:00:00.023678
2020-07-24 06:02:29,952 - INFO - 	 Inference time: 0:00:00.024716
2020-07-24 06:02:30,007 - INFO - 	 Inference time: 0:00:00.024368
2020-07-24 06:02:30,062 - INFO - 	 Inference time: 0:00:00.023714
2020-07-24 06:02:30,126 - INFO - 	 Inference time: 0:00:00.023561

--------------------------------------------------------------------------------

It looks like an opencv error to actually view the video while executing code. I am sure that colab won't allow to show the detection while running the code. I could be wrong but could you please suggest me something about this error? 
Thanks in advance!

**Comment by GlassyWing** [comment]
Thanks for report, this is not a serious problem, but a logical problem of imutils. You can ignore it directly now. While, you can fix that by changing the code:
https://github.com/GlassyWing/yolo_deepsort/blob/747f38744d406b759108727b70031291a00270bc/yolo3/detect/video_detect.py#L33
to 
```py
def _transform(frame):
    if frame is not None:
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    return frame
```

**Comment by GlassyWing** [comment]
The bug has fixed, now you can pull the latest code.

**Comment by err-or** [comment]
Thank you very much for such a quick response. It did fix the bug.
